-- 1. Players (From official list)
create table players (
  id bigint primary key, -- External ID (e.g., 5585)
  name text not null,
  role text not null, -- 'P', 'D', 'C', 'A'
  team_real text not null, -- Serie A Team
  quotation int default 1
);

-- 2. Leagues (Single league for now)
create table leagues (
  id uuid default gen_random_uuid() primary key,
  name text not null
);

-- 3. Fantasy Teams (Users)
create table teams (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  league_id uuid references leagues,
  name text not null,
  credits_left int default 1000, -- Auction starts at 1000
  created_at timestamp with time zone default now()
);

-- 4. Rosters (Which team owns which player)
create table rosters (
  id bigint generated by default as identity primary key,
  team_id uuid references teams not null,
  player_id bigint references players not null,
  purchase_price int default 0,
  unique(team_id, player_id)
);

-- 5. Fixtures (Calendar)
create table fixtures (
  id bigint generated by default as identity primary key,
  league_id uuid references leagues,
  matchday int not null, -- 1 to 38
  home_team_id uuid references teams,
  away_team_id uuid references teams,
  home_goals int default 0,
  away_goals int default 0,
  calculated boolean default false
);

-- 6. Lineups (Submitted formations)
create table lineups (
  id bigint generated by default as identity primary key,
  fixture_id bigint references fixtures not null,
  team_id uuid references teams not null,
  module text not null, -- e.g., '3-4-3'
  created_at timestamp with time zone default now()
);

-- 7. Lineup Players (Detailed selection)
create table lineup_players (
  id bigint generated by default as identity primary key,
  lineup_id bigint references lineups not null,
  player_id bigint references players not null,
  is_starter boolean default false,
  bench_order int default 0 -- 0 for starters, 1 for 1st sub, etc.
);

-- 8. Match Stats (Weekly Votes imported by Admin)
create table match_stats (
  id bigint generated by default as identity primary key,
  player_id bigint references players not null,
  matchday int not null,
  vote float, -- Raw vote (e.g. 6.5)
  goals_for int default 0,
  goals_against int default 0,
  assists int default 0,
  yellow_cards int default 0,
  red_cards int default 0,
  penalties_saved int default 0,
  penalties_missed int default 0,
  own_goals int default 0
);
-- 9. System Logs (Admin Audit)
create table logs (
  id bigint generated by default as identity primary key,
  user_id uuid, -- Link to auth.users if available, but nullable (e.g. system events)
  action text not null, -- e.g. 'TEAM_CREATED', 'PLAYER_BOUGHT'
  details jsonb, -- Flexible metadata
  created_at timestamp with time zone default now()
);

-- 10. Trade Proposals
create table trade_proposals (
  id bigint generated by default as identity primary key,
  proposer_team_id uuid references teams not null,
  receiver_team_id uuid references teams not null,
  proposer_player_id bigint references players not null,
  receiver_player_id bigint references players not null,
  credits_offer int default 0, -- Amount proposer PAYS to receiver
  status text default 'PENDING', -- PENDING, ACCEPTED, REJECTED, CANCELLED
  created_at timestamp with time zone default now()
);

-- 11. Market Settings
create table settings (
  key text primary key,
  value text not null
);

-- Insert default settings
insert into settings (key, value) values 
('auction_duration_hours', '24'),
('snippet_threshold_seconds', '30'),
('snippet_extension_minutes', '2'),
('market_open_hour', '8'),
('market_close_hour', '22');

-- 12. Auctions
create table auctions (
  id bigint generated by default as identity primary key,
  player_id bigint references players not null,
  current_price int default 1,
  current_winner_team_id uuid references teams,
  end_time timestamp with time zone not null,
  status text default 'OPEN', -- OPEN, CLOSED
  created_at timestamp with time zone default now()
);
